language: c
compiler:
  - gcc
  - clang
script:
  - "cmake -DBUILD_RELEASE_TYPE=RelWithDebInfo && make"
before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install -y libprotobuf-c-dev libev-dev"
