language: c
compiler:
  - gcc
  - clang
env:
  - PROTOBUF_VERSION=2.6.0
script:
  - "cmake -DBUILD_RELEASE_TYPE=RelWithDebInfo && make"
before_install:
  - "sudo apt-get update"
  - "git clone --depth=50 https://github.com/protobuf-c/protobuf-c.git"
  - "wget https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-$PROTOBUF_VERSION.tar.gz"
install:
  - "sudo apt-get install -y libev-dev"
  - "tar xzf protobuf-$PROTOBUF_VERSION.tar.gz"
  - "cd protobuf-$PROTOBUF_VERSION && ./configure && make -j2 && sudo make install && sudo ldconfig && cd .."
  - "cd protobuf-c && ./autogen.sh && ./configure && make && sudo make install"
