language: c
compiler:
  - gcc
  - clang
script:
  - "cmake -DBUILD_RELEASE_TYPE=RelWithDebInfo && make"
before_install:
  - "sudo apt-get update"
  - "git clone https://github.com/protobuf-c/protobuf-c.git"
install:
  - "sudo apt-get install -y libev-dev libprotobuf-dev protobuf-compiler libprotoc-dev"
  - "cd protobuf-c && ./autogen.sh && ./configure && make && sudo make install"

