language: c
compiler:
  - gcc
  - clang
env:
  - PROTOBUF_VERSION=2.6.0
  global:
    - secure: "R9N091rGRGfns4QML1hhJHiFLJRLEzS5dwayOHIHgm0bT9KkCrjKgAzphdD8PLrkEue6EWmkOcsO/EAJf6bvri9kL4nbI0fxWrWbyf77f9VKMQYpj9Wu66zh5VA1QNfh5IcKoKKfn9RhMnyxqXkli2EV6lTWDktLUfinZJXrsxA="
script:
  - "if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j2; fi"
before_install:
  - "sudo apt-get update"
  - "git clone --depth=50 https://github.com/protobuf-c/protobuf-c.git"
  - "wget https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protobuf-$PROTOBUF_VERSION.tar.gz"
install:
  - "sudo apt-get install -y libev-dev"
  - "tar xzf protobuf-$PROTOBUF_VERSION.tar.gz"
  - "cd protobuf-$PROTOBUF_VERSION && ./configure && make -j2 && sudo make install && sudo ldconfig && cd .."
  - "cd protobuf-c && ./autogen.sh && ./configure && make -j2 && sudo make install && cd .."
addons:
  coverity_scan:
    project:
      name: "mkroman/libmumble"
      description: "Mumble client library in C."
    build_command: "make -j2"
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo"
    branch_pattern: "coverity"
    notification_email: "mk+libmumble@maero.dk"
